language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
- stable
before_install:
- npm install -g typings
before_script:
- npm run prepare
script:
- npm run test:offline
