language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "stable"

before_install:
  - npm install -g typings
  - openssl aes-256-cbc -K $encrypted_022e925ff3dd_key -iv $encrypted_022e925ff3dd_iv -in test-config.js.enc -out test-config.js -d

before_script:
  - npm run prepare

script:
  - npm test
